export const API_ENDPOINTS = {
  RESTAURANTS: '/api/restaurants',
  REVIEWS: '/api/reviews',
  review: (id: string) => `/api/reviews/${id}`,
  reviewHelpful: (id: string) => `/api/reviews/${id}/helpful`,
  reviewFlag: (id: string) => `/api/reviews/${id}/flag`,
  DISHES: '/api/dishes',
  dishReviews: (id: string) => `/api/dishes/${id}/reviews`,
  restaurantAnalytics: (id: string) => `/api/restaurants/${id}/analytics`,
  restaurantClaim: (id: string) => `/api/restaurants/${id}/claim`,
  wishlistItem: (userId: string, dishId: string) =>
    `/api/users/${userId}/wishlist/${dishId}`,
  NOTIFICATIONS_UNREAD_COUNT: '/api/notifications/unread-count',
  NOTIFICATIONS_READ_ALL: '/api/notifications/read-all',
  REWARDS_BALANCE: '/api/rewards/balance',
  REWARDS_COUPONS: '/api/rewards/coupons',
  REWARDS_CLAIMS: '/api/rewards/claims',
  REWARDS_REDEEM: '/api/rewards/redeem',
  BILLING_CREATE_ORDER: '/api/billing/create-order',
  BILLING_VERIFY: '/api/billing/verify',
  ADMIN_COUPONS: '/api/admin/coupons',
  adminCoupon: (id: string) => `/api/admin/coupons/${id}`,
  adminDishRequest: (id: string) => `/api/admin/dish-requests/${id}`,
  ADMIN_RESTAURANT_CLAIMS: '/api/admin/restaurant-claims',
  adminReview: (id: string) => `/api/admin/reviews/${id}`,
  adminUserRole: (userId: string) => `/api/admin/users/${userId}/role`,
  adminUserPremium: (userId: string) => `/api/admin/users/${userId}/premium`,
} as const
